steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/sit737-23t1-mishra-80a3f52/jokes-image', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/sit737-23t1-mishra-80a3f52/jokes-image']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['container', 'clusters', 'get-credentials', 'cluster-1', '--region', 'australia-southeast1']

  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'deployment.yaml']
